config/routes.rb
Rails.application.routes.draw do

  # =========================デバイスの機能を絞る設定==============================
  devise_for :admins, skip: :all

  devise_scope :admin do
    get 'login', to: 'devise/sessions#new', as: 'new_admin_session'
    post 'login', to: 'devise/sessions#create', as: 'admin_session'
    delete 'logout', to: 'devise/sessions#destroy', as: 'destroy_admin_session'
  end
  # ===========================================================================

  # トップページをitemsのindexに設定
  root 'items#index'

  # namespaceでadmin配下にitemsを配置
  namespace :admin do
    resources :items
    resources :purchased_histories, only: [:index, :show]
    put 'statuschange/:id', to: 'items#statuschange', as: 'statuschange'
    get 'confirm/:id', to: 'items#confirm', as: 'confirm'
    put 'shippingchange/:id', to: 'purchased_histories#shippingchange', as: 'shippingchange'
  end

  # 一般のページ
  resources :items, only: [:index, :show, :create]
  resources :purchased_histories, only: [:new, :create]
  post 'purchased_histories/sessioncreate', to: 'purchased_histories#sessioncreate', as: 'sessioncreate'
  get 'purchased_histories/sessiondestroy/:id', to: 'purchased_histories#sessiondestroy', as: 'sessiondestroy'

  # refilegem用
  resources :post_images, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    acts_as_paranoid
  # ==========================アソシエーション====================================
  has_many :post_images
  has_many :item_tags
  has_many :tags, through: :item_tags
  has_many :purchased_items
  has_many :purchased_histories, through: :purchased_items
  has_one  :stock
  # ===========================================================================

  # ============================gem要設定=======================================
  # refile用
  accepts_attachments_for :post_images, attachment: :image
  # ===========================================================================

  # ====================formにhasmanyをネストさせる===============================
  accepts_nested_attributes_for :stock, allow_destroy: true
  accepts_nested_attributes_for :item_tags, allow_destroy: true
  accepts_nested_attributes_for :tags
  # ===========================================================================


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::Base
  # 上記の < Admin::Baseでbase.rbを継承するように指示
  before_action :authenticate_admin!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET admin_items GET    /admin/items 管理者画面のトップページ
  def index
    if params[:search].present?
      # Tagを検索しItemを取り出す
      tags = Tag.where('tag_name LIKE ?', "%#{params[:search]}%")
      # ユーザー名を検索しPurchasedHistoryを取り出す
      purchased_histories = PurchasedHistory.where('user_name LIKE ?', "%#{params[:search]}%")
      if tags.present?
        # タグが取り出せた場合
        item_tags = tags.map { |tag| ItemTag.where(tag_id: tag.id) }
        @items = item_tags.flatten!.map { |item_tag| Item.find_by(id: item_tag.item_id) }.uniq
        # @searchedは次jsファイルの条件分岐用
        @searched = 'item'
      elsif purchased_histories.present?
        # ユーザー名が取り出せた場合
        @items_with_deleted = Item.with_deleted
        @purchased_histories = purchased_histories.order(created_at: "DESC")
        @searched = 'username'
      else
        # タグが見つからない場合通常表示
        @items = Item.all.order(created_at: "DESC")
        @items_with_deleted = Item.with_deleted
        @purchased_histories = PurchasedHistory.all.order(created_at: "DESC")
        @searched = 'all'
      end
    else
      # 通常表示
      @items = Item.all.order(created_at: "DESC")
      @items_with_deleted = Item.with_deleted
      @purchased_histories = PurchasedHistory.all.order(created_at: "DESC")
      @searched = 'all'
    end
  end

  # GET admin_item GET    /admin/items/:id アイテムのQRコード表示
  def show
    @item = Item.find(params[:id])
    # svgでqr生成
    @qr = RQRCode::QRCode.new(@item.item_qr).as_svg.html_safe
  end

  # new_admin_item GET    /admin/items/new アイテム新規登録フォーム表示
  def new
    @item = Item.new
    @tags = Tag.new
    # refileで画像を投稿できるようにしている
    @item.post_images.build
    @item.item_description = "まねきねこはねこです。"
    @item.build_stock
  end

  # admin_items POST   /admin/items アイテム新規登録フォームの登録
  def create
    # gem cocoonによりネストした増殖フォームは上手に保存してくれている
    @item = Item.new(item_params)
    @tag = Tag.new(tag_params)
    respond_to do |format|
      if @item.save
        # 一個目のタグ新規追加フォームは以下で制御
        if @tag.tag_name?
          # タグが空欄の場合保存しないようにする
          @tag.save
          ItemTag.create(item_id: @item.id, tag_id: @tag.id)
        end
        # QRコードのURLを生成
        @item.item_qr = "https://portfolio.amamo.site/#Item#{@item.id}"
        @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
        format.js   { @status = "success"}
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
        format.js   { @status = "fail" }
      end
    end
  end

  # edit_admin_item GET    /admin/items/:id/edit アイテムの編集ページ
  def edit
    @item = Item.find(params[:id])
    @tags = Tag.new
  end

  # admin_item PUT    /admin/items/:id アイテム編集登録
  def update
    # gem cocoonによりネストした増殖フォームは上手に保存してくれている
    @item = Item.find(params[:id])
    @tag = Tag.new(tag_params)
    respond_to do |format|

      if @item.update(item_params)
        # 一個目のタグ新規追加フォームは以下で制御
        if @tag.tag_name?
          # タグが空欄の場合保存しないようにする
          @tag.save
          ItemTag.create(item_id: @item.id, tag_id: @tag.id)
        end
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
        format.js   { @status = "success"}
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
        format.js   { @status = "fail" }
      end
    end
  end

  # admin_statuschange PUT    /admin/statuschange/:id item_active変更
  def statuschange
    @item = Item.find(params[:id])
    if @item.item_active == 0
      @item.item_active = 1
      @item.save
    else
      @item.item_active = 0
      @item.save
    end
  end

  # admin_confirm GET    /admin/confirm/:id 商品削除確認画面
  def confirm
    @item = Item.find(params[:id])
  end

  # admin_item DELETE /admin/items/:id 商品削除確認画面から商品の削除
  def destroy
    respond_to do |format|
      if @item.destroy
        format.html { redirect_to admin_items_path, notice: 'Item was successfully destroyed.' }
        format.json { head :no_content }
        format.js   { @status = "success"}
      else
        format.html { redirect_to admin_items_path, notice: 'Item was error destroyed.' }
        format.json { head :no_content }
        format.js   { @status = "fail" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(
        :item_name, :item_description, :item_image_id, :item_qr, :item_price, :item_active,
        post_images_images: [],
        stock_attributes: [:id, :item_id, :stock_count],
        tags_attributes: [:id, :tag_name, :_destroy],
        tag_ids: [])
      # 複数画像を投稿できるように[]をつけている
      # フォームにhasoneのstockを含めている
    end

    def tag_params
      params.require(:tag).permit(:tag_name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # items GET    /items トップページ
  def index
    # カートで使用するSession確認
    if session[:cart] == nil
      session[:cart] = {}
    else
      @cart = session[:cart].map { |item_id, item_count| Item.find(item_id.to_i) }
    end
    # 商品検索
    @items = if params[:search].present?
      # Tagを検索しItemを取り出す
      tags = Tag.where('tag_name LIKE ?', "%#{params[:search]}%")
      if tags.present?
        item_tags = tags.map { |tag| ItemTag.where(tag_id: tag.id) }
        @items = item_tags.flatten!.map { |item_tag| Item.find_by(id: item_tag.item_id) }.uniq
      else
        # タグが見つからない場合
        Item.all.order(created_at: "DESC")
      end
    else
      # 通常表示
      Item.all.order(created_at: "DESC")
    end
  end

  # item GET    /items/:id アイテムの詳細ページ
  def show
    @item = Item.find(params[:id])
    @tax_included = (BigDecimal(@item.item_price) * BigDecimal("1.08")).ceil
    @purchased_history = PurchasedHistory.new
    @purchased_item = PurchasedItem.new
  end

  def create
    # アップルペイ本番仕様の場合以下を利用
    # begin
    # payjp決済確定
    # Payjp.api_key = ENV['PAYJP_TEST_SECRET_KEY']
    # Payjp::Charge.create(
    #   :amount => "1000",
    #   :card => params['payjp-token'],
    #   :currency => 'jpy',
    # )
    # purchased_history_save
    # redirect_to root_path
    # rescue Payjp::CardError
    #   respond_to do |format|
    #     format.html { redirect_to root_path, notice: 'カードエラーが発生しました' }
    #   end
    # end
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_history_params
      params.require(:purchase_history).permit(:user_name, :postal_code, :address, :phone_number, :email_address, :shipping, purchased_items_attributes: [:id, :purchased_history_id, :item_id, :item_count, :_destroy])
      # 複数画像を投稿できるように[]をつけている
      # フォームにhasoneのstockを含めている
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/_edit.html.erb
<!-- Modalボディ部分 -->
<%# adminをnamespase化している為model: [ :admin, @item ]として指定 %>
<%= form_with model: [ :admin, @item ],url: admin_item_path(@item.id), method: :put do |form| %>

<div class="modal-body">
  <!-- row -->
  <div class="container-fluid bd-example-row">
    <!-- render用div -->
    <div id="NewItem"></div>

    <!-- エラー時使用 -->
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %>
          prohibited this item from being saved:</h2>
        <ul>
          <% item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :item_name, "商品名" %>
        <%= form.text_field :item_name, class: "form-control", placeholder: "日本人形" %>
        <%= form.label :post_images_images, "商品画像" %>
        <%= form.attachment_field :post_images_images, multiple: true, class: "form-control-file" %>
        <%= form.label :item_price, "金額" %>
        <%= form.number_field :item_price, class: "form-control", placeholder: "税抜きカンマ不要" %>
        <%= form.fields_for :stock do |fin| %>
        <%= fin.label :stock_count, "在庫数" %>
        <%= fin.number_field :stock_count, class: "form-control", placeholder: "半角" %>
        <% end %>
      </div>

      <!-- 画像表示 -->
      <div class="form-group col-md-6">
        <div class="preview">
          <% if @item.post_images.present? %>
            <% @item.post_images.each do |image| %>
              <%= attachment_image_tag image, :image, width: "100%" %>
            <% end %>
          <% else %>
            <%= image_tag '/images/no_image.jpg', width: "100%" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :item_description, "商品説明" %>
      <%= form.text_area :item_description, class: "form-control", rows: "3" %>
    </div>

    <!-- タグ選択とネストフォームを横一列にするdiv -->
    <div class="form-row">
      <div class="form-group col-md-4">
        <label>タグ選択</label>
        <div class="form_control">
          <%= collection_check_boxes(:item, :tag_ids, Tag.all, :id, :tag_name) do |tag_name| %>
            <%= tag_name.label do %>
              <%= tag_name.check_box %>
              <%= tag_name.text %>
            <% end %>
          <% end %>
        </div>
      </div>

      <!-- ネストフォーム開始 -->
      <div class="col-md-8">
        <div class="row">
          <%= fields_for :tag, @Tag do |tag| %>
            <%= tag.label :tag_name, "タグ入力" %>
        </div>
        <div class="row">
          <div class="form-group col-8">
            <%= tag.text_field :tag_name, class: "form-control", placeholder: "新規追加の場合入力して下さい" %>
          </div>
          <div id="links" class="form-group col-4 d-flex">
            <%= link_to_add_association "追加", form, :tags, class: "btn btn-link" %>
          </div>
        </div>
          <% end %>
      </div>
    <!-- ネストフォーム終了 -->
    </div>
  <!-- タグ選択とネストフォームを横一列にするDiv -->
  </div>
<!-- row終了 -->
</div>
<!-- Modalボディ部分終了 -->


<!-- Modalフッター部分 -->
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  <%= link_to "削除", admin_confirm_path(@item), remote: true, class: "btn btn-outline-light active text-danger" %>
  <%= form.submit "編集完了", class: "btn btn-primary" %>
</div>
<% end %>

<script type="text/javascript">
$(function () {
//画像ファイルプレビュー表示のイベント追加 fileを選択時に発火するイベントを登録
$('form').on('change', 'input[type="file"]', function (e) {
var file = e.target.files[0],
reader = new FileReader(),
$preview = $(".preview");
t = this;

// 画像ファイル以外の場合は何もしない
if (file.type.indexOf("image") < 0) {
return false;
}

// ファイル読み込みが完了した際のイベント登録
reader.onload = (function (file) {
return function (e) {
  //既存のプレビューを削除
  $preview.empty();
  // .prevewの領域の中にロードした画像を表示するimageタグを追加
  $preview.html($('<img>').attr({src: e.target.result, width: "100%", class: "preview", title: file.name}));
};
})(file);

reader.readAsDataURL(file);
});
});

//フォームエンター制御変更
$("input").keydown(function (e) {
if ((e.which && e.which === 13) || (e.keyCode && e.keyCode === 13)) {
return false;
} else {
return true;
}
});
</script>

app/views/admin/items/_form.html.erb
<!-- Modalボディ部分 -->
<%# adminをnamespase化している為model: [ :admin, @item ]として指定 %>
<%= form_with model: [ :admin, @item ] do |form| %>

<div class="modal-body">
  <!-- row -->
  <div class="container-fluid bd-example-row">
    <!-- render用div -->
    <div id="NewItem"></div>

    <!-- エラー時表示 -->
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %>
          prohibited this item from being saved:</h2>
        <ul>
          <% item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :item_name, "商品名" %>
        <%= form.text_field :item_name, class: "form-control", placeholder: "日本人形", id: "item_name" %>
        <%= form.label :post_images_images, "商品画像" %>
        <%= form.attachment_field :post_images_images, multiple: true, class: "form-control-file" %>
        <%= form.label :item_price, "金額" %>
        <%= form.number_field :item_price, class: "form-control", placeholder: "税抜きカンマ不要" %>
        <%= form.fields_for :stock do |stock| %>
        <%= stock.label :stock_count, "在庫数" %>
        <%= stock.number_field :stock_count, class: "form-control", placeholder: "半角" %>
        <% end %>
      </div>
      <div class="form-group col-md-6">
        <div class="preview"></div>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :item_description, "商品説明" %>
      <%= form.text_area :item_description, class: "form-control", rows: "3" %>
    </div>

    <!-- タグ選択とネストフォームを横一列にするdiv -->
    <div class="form-row">
      <div class="form-group col-md-4">
        <label>タグ選択</label>
        <div class="form_control">
          <%= collection_check_boxes(:item, :tag_ids, Tag.all, :id, :tag_name) do |tag_name| %>
            <%= tag_name.label do %>
              <%= tag_name.check_box %>
              <%= tag_name.text %>
            <% end %>
          <% end %>
        </div>
      </div>

    <!-- ネストフォーム開始 -->
    <div class="col-md-8">
      <div class="row">
        <%= fields_for :tag, @Tag do |tag| %>
        <%= tag.label :tag_name, "タグ入力" %>
      </div>
      <div class="row">
        <div class="form-group col-8">
          <%= tag.text_field :tag_name, class: "form-control", placeholder: "新規追加の場合入力して下さい", id: "tag" %>
        </div>
        <div id="links" class="form-group col-4 d-flex">
          <%= link_to_add_association "追加", form, :tags, class: "btn btn-link" %>
        </div>
      </div>
        <% end %>
    </div>
    <!-- ネストフォーム終了 -->
  </div>
  <!-- タグ選択とネストフォームを横一列にするDiv -->
  </div>
<!-- row終了 -->
</div>
<!-- Modalボディ部分終了 -->

<!-- Modalフッター部分 -->
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  <%= form.submit "登録", class: "btn btn-primary" %>
</div>
<% end %>

<script type="text/javascript">
$(function () {
// =======================画像のプレビュー表示制御=================================
// 画像ファイルプレビュー表示のイベント追加 fileを選択時に発火するイベントを登録
$('form').on('change', 'input[type="file"]', function (e) {
var file = e.target.files[0],
reader = new FileReader(),
$preview = $(".preview");
t = this;

// 画像ファイル以外の場合は何もしない
if (file.type.indexOf("image") < 0) {
return false;
}

// ファイル読み込みが完了した際のイベント登録
reader.onload = (function (file) {
return function (e) {
  //既存のプレビューを削除
  $preview.empty();
  // .prevewの領域の中にロードした画像を表示するimageタグを追加
  $preview.append($('<img>').attr({src: e.target.result, width: "100%", class: "preview", title: file.name}));
};
})(file);

reader.readAsDataURL(file);
});
// ============================================================================

// ============================フォーム同時入力制御===============================
$('#item_name').on("keyup change", function () {
$("#tag").val($(this).val());
});
//フォームエンター制御変更
  $("input").keydown(function(e) {
    if ((e.which && e.which === 13) || (e.keyCode && e.keyCode === 13)) {
      return false;
    } else {
      return true;
    }
  });
// ============================================================================

});
</script>

app/views/admin/items/_searched.html.erb
<!-- 繰り返し開始 -->
<% if items.present? %>
  <% items.each do |item| %>
  <% if item.present? %>
    <tr id=<%= "item#{item.id}" %>>
      <th scope="row">
        <%= link_to edit_admin_item_path(item), remote: true, class: "table-innercustom-a area-all" do %>
        <%= item.id %>
      <% end %>
    </th>
    <td>
      <%= link_to edit_admin_item_path(item), remote: true, class: "table-innercustom-a area-all" do %>
      <%= item.item_name %>
    <% end %>
  </td>
  <td>
    <%= link_to edit_admin_item_path(item), remote: true, class: "table-innercustom-a area-all" do %>
    <%= item.item_price %>
  <% end %>
</td>

<td>
  <%= link_to edit_admin_item_path(item), remote: true, class: "table-innercustom-a area-all" do %>
  <% if item.stock.present? %>
    <%= item.stock.stock_count %>
  <% end %>
<% end %>
</td>
<td>
<%= link_to admin_item_path(item), remote: true, class: "btn btn-outline-light active table-innercustom-a" do %>
<i class="fas fa-qrcode"></i>
<% end %>
</td>
<td id=<%= "statuschange#{item.id}" %> >
<% if item.item_active == 0 %>
<%= link_to '未販売', admin_statuschange_path(item), remote: true, method: :put, class: "btn btn-outline-light active table-innercustom-a text-danger" %>
<% else %>
<%= link_to '販売中', admin_statuschange_path(item), remote: true, method: :put, class: "btn active btn-outline-light table-innercustom-a text-success" %>
<% end %>
</td>
</tr>
<% end %>
<% end %>
<% end %>
<!-- 繰り返し終了 -->

app/views/admin/items/_searched_item.html.erb
<!-- 繰り返し開始 -->
<% if items.present? %>
  <% items.each do |item| %>
    <% if item.present? %>
      <tr id=<%= "item#{item.id}" %>>
        <th scope="row">
          <%= link_to edit_admin_item_path(item), remote: true, class: "table-innercustom-a area-all" do %>
          <%= item.id %>
          <% end %>
        </th>
        <td>
          <%= link_to edit_admin_item_path(item), remote: true, class: "table-innercustom-a area-all" do %>
          <%= item.item_name %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_admin_item_path(item), remote: true, class: "table-innercustom-a area-all" do %>
          <%= item.item_price %>
          <% end %>
        </td>

        <td>
          <%= link_to edit_admin_item_path(item), remote: true, class: "table-innercustom-a area-all" do %>
            <% if item.stock.present? %>
              <%= item.stock.stock_count %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to admin_item_path(item), remote: true, class: "btn btn-outline-light active table-innercustom-a" do %>
            <i class="fas fa-qrcode"></i>
          <% end %>
        </td>
        <td id=<%= "statuschange#{item.id}" %>>
        <% if item.stock.present? && item.stock.stock_count == 0 %>
          <%= link_to '在庫0', edit_admin_item_path(item), remote: true, class: "btn btn-outline-light active table-innercustom-a text-warning" %>
        <% else %>
          <% if item.item_active == 0 %>
            <%= link_to '未販売', admin_statuschange_path(item), remote: true, method: :put, class: "btn btn-outline-light active table-innercustom-a text-danger" %>
          <% else %>
            <%= link_to '販売中', admin_statuschange_path(item), remote: true, method: :put, class: "btn active btn-outline-light table-innercustom-a text-success" %>
          <% end %>
        <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
<% end %>
<!-- 繰り返し終了 -->

app/views/admin/items/_searched_username.html.erb
<!-- 繰り返し開始 -->
<% if purchased_histories.present? %>
  <% purchased_histories.each do |purchased_history| %>
    <% purchased_items = PurchasedItem.where(purchased_history_id: purchased_history.id) %>
    <% final_price = 0 %>
      <% purchased_items.each do |purchased_item| %>
        <% item_price = items_with_deleted.find(purchased_item.item_id).item_price %>
        <% tax_included_item_price = (BigDecimal(item_price) * BigDecimal("1.08")).ceil %>
        <% total_price = tax_included_item_price * purchased_item.item_count.to_i %>
        <% final_price = final_price + total_price %>
      <% end %>

      <tr id=<%= "purchased-history#{purchased_history.id}" %>>
        <th scope="row">
          <%= link_to admin_purchased_history_path(purchased_history), remote: true, class: "table-innercustom-a area-all" do %>
          <%= purchased_history.id %>
          <% end %>
        </th>

        <td>
          <%= link_to admin_purchased_history_path(purchased_history), remote: true, class: "table-innercustom-a area-all" do %>
          <%= purchased_history.created_at.strftime('%Y年%m月%d日') %>
          <% end %>
        </td>

        <td>
          <%= link_to admin_purchased_history_path(purchased_history), remote: true, class: "table-innercustom-a area-all" do %>
          <%= purchased_history.user_name %>
          <% end %>
        </td>

        <td>
          <%= link_to admin_purchased_history_path(purchased_history), remote: true, class: "table-innercustom-a area-all" do %>
          <%= final_price %>円
          <% end %>
        </td>

        <td id=<%= "shippingchange#{purchased_history.id}" %> >
          <% if item.stock.present? && item.stock.stock_count == 0 %>
            <%= link_to '在庫0', edit_admin_item_path(item), remote: true, class: "btn btn-outline-light active table-innercustom-a text-warning" %>
          <% else %>
            <% if item.item_active == 0 %>
              <%= link_to '未販売', admin_statuschange_path(item), remote: true, method: :put, class: "btn btn-outline-light active table-innercustom-a text-danger" %>
            <% else %>
              <%= link_to '販売中', admin_statuschange_path(item), remote: true, method: :put, class: "btn active btn-outline-light table-innercustom-a text-success" %>
            <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
<% end %>
<!-- 繰り返し終了 -->

app/views/admin/items/_show.html.erb
<!-- Modalヘッダー部分 -->
<div class="modal-header">
  <h5 class="modal-title" id="qrItemModalLabel"><%= item.item_name %></h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">×</span></button>
</div>
<!-- Modalボディ部分 -->
<div class="modal-body">
  <div class="container-fluid bd-example-row text-center mx-auto responsive-qr-fit">
    <%= @qr %>
  </div>
</div>
<!-- Modalボディ部分終了 -->

app/views/admin/items/_statuschange.html.erb
<% if item.item_active == 0 %>
  <%= link_to '未販売', admin_statuschange_path(item), remote: true, method: :put, class: "btn btn-outline-light active table-innercustom-a text-danger" %>
<% else %>
  <%= link_to '販売中', admin_statuschange_path(item), remote: true, method: :put, class: "btn active btn-outline-light table-innercustom-a text-success" %>
<% end %>

app/views/admin/items/destroy.js.erb
console.log('hi');
<% if @status == 'success' %>
  location.reload();
  $("#delOKModal").modal("hide");
<%  elsif @status == 'fail' %>
  alert('error!');
<% end %>

app/views/admin/items/edit.js.erb
// index.html.erb中のDivに対して、新規作成用のformをレンダリング
console.log('hi');
$("#EditItem").html("<%= escape_javascript(render 'edit', item: @item) %>");
// デフォルトのbootstrapでmodalを開いても良いが、タイミングが早すぎてrender間に合わない
$("#NewItemModal").modal("show");

app/views/admin/items/index.js.erb
var searched = "<%= @searched %>";
console.log(searched);
if ( searched == 'item' ) {
  // itemが取り出せている場合
  console.log('item');
  $('#searched_item').html("<%= escape_javascript(render 'searched_item', items: @items) %>");
  // クリックして該当場所に移動
  $('#nav-home-tab').click();
} else if ( searched == 'username' ) {
  // ユーザー名が取り出せている場合
  console.log('name');
  $('#searched_user_name').html("<%= escape_javascript(render 'searched_username', purchased_histories: @purchased_histories, items_with_deleted: @items_with_deleted) %>");
  $('#nav-profile-tab').click();
} else if ( searched == 'all' ) {
  // 空白の場合
  console.log('all');
$('#searched_item').html("<%= escape_javascript(render 'searched_item', items: @items) %>");
$('#searched_user_name').html("<%= escape_javascript(render 'searched_username', purchased_histories: @purchased_histories, items_with_deleted: @items_with_deleted) %>");
$('#nav-home-tab').click();
} else {
  console.log('該当なし');
}

app/views/admin/items/new.js.erb
// index.html.erb中のDivに対して、新規作成用のformをレンダリング
$("#NewItem").html("<%= escape_javascript(render 'form', item: @item) %>");
// デフォルトのbootstrapでmodalを開いても良いが、タイミングが早すぎてrender間に合わない
$("#createItemModal").modal("show");

app/views/admin/items/show.js.erb
// index.html.erb中のDivに対して、新規作成用のformをレンダリング
console.log('hi');
$("#ShowItem").html("<%= escape_javascript(render 'show', item: @item) %>");
// デフォルトのbootstrapでmodalを開いても良いが、タイミングが早すぎてrender間に合わない
$("#qrItemModal").modal("show");

app/views/admin/items/statuschange.js.erb
$("#<%= "statuschange#{@item.id}" %>").html("<%= escape_javascript(render 'statuschange', item: @item) %>");