config/routes.rb
Rails.application.routes.draw do

  # =========================デバイスの機能を絞る設定==============================
  devise_for :admins, skip: :all

  devise_scope :admin do
    get 'login', to: 'devise/sessions#new', as: 'new_admin_session'
    post 'login', to: 'devise/sessions#create', as: 'admin_session'
    delete 'logout', to: 'devise/sessions#destroy', as: 'destroy_admin_session'
  end
  # ===========================================================================

  # トップページをitemsのindexに設定
  root 'items#index'

  # namespaceでadmin配下にitemsを配置
  namespace :admin do
    resources :items
    resources :purchased_histories, only: [:index, :show]
    put 'statuschange/:id', to: 'items#statuschange', as: 'statuschange'
    get 'confirm/:id', to: 'items#confirm', as: 'confirm'
    put 'shippingchange/:id', to: 'purchased_histories#shippingchange', as: 'shippingchange'
  end

  # 一般のページ
  resources :items, only: [:index, :show, :create]
  resources :purchased_histories, only: [:new, :create]
  post 'purchased_histories/sessioncreate', to: 'purchased_histories#sessioncreate', as: 'sessioncreate'
  get 'purchased_histories/sessiondestroy/:id', to: 'purchased_histories#sessiondestroy', as: 'sessiondestroy'

  # refilegem用
  resources :post_images, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/purchased_history.rb
class PurchasedHistory < ApplicationRecord
  # ==========================アソシエーション====================================
  has_many :purchased_items
  has_many :items, through: :purchased_items
  # ===========================================================================
  
  # ====================formにhasmanyをネストさせる===============================
  accepts_nested_attributes_for :purchased_items, allow_destroy: true
  # ===========================================================================
end

app/controllers/admin/purchased_histories_controller.rb
class Admin::PurchasedHistoriesController < Admin::Base
  before_action :set_purchased_history, only: [:show, :edit, :update, :destroy]

  # admin_purchased_histories GET    /admin/purchased_histories 注文履歴表示画面
  def index
    @purchased_histories = PurchasedHistory.all
  end

  # admin_purchased_history GET    /admin/purchased_histories/:id 注文履歴詳細表示
  def show
    @purchased_history = PurchasedHistory.find(params[:id])
    @purchased_items = PurchasedItem.where(purchased_history_id: @purchased_history.id)
    @items_with_deleted = Item.with_deleted
  end

  # admin_shippingchange PUT    /admin/shippingchange/:id 注文のshipping変更
  def shippingchange
    @purchased_history = PurchasedHistory.find(params[:id])
    if @purchased_history.shipping == 0
      @purchased_history.shipping = 1
      @purchased_history.save
    else
      @purchased_history.shipping = 0
      @purchased_history.save
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchased_history
      @purchased_history = PurchasedHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchased_history_params
      params.require(:purchased_history).permit(:user_name, :postal_code, :address, :phone_number, :email_address, :shipping, :created_at, :updated_at)
    end
end

app/controllers/purchased_histories_controller.rb
class PurchasedHistoriesController < ApplicationController
  before_action :set_purchased_history, only: [:show, :edit, :update, :destroy]

  # GET /purchased_histories/new
  def new
    @cart = session[:cart].map { |item_id, item_count| Item.find(item_id.to_i) }
    @purchased_history = PurchasedHistory.new
    @purchased_item = PurchasedItem.new
    respond_to do |format|
      format.js
    end
  end

  # purchased_histories POST   /purchased_histories カート画面フォームのsubmit後
  def create
    if params[:close]# カートの閉じるボタン後
      if session[:cart].present?
        session[:cart] = params[:purchased_item]
      end
    elsif params[:update]# カートの在庫更新ボタン後
      if session[:cart].present?
        params[:purchased_item].each do |item_id, item_count|
          item = Item.find(item_id.to_i)
          stock = Stock.find_by(item_id: item.id)
          stock.stock_count = item_count["item_count"].to_i
          stock.save
          session[:cart].delete(item_id)
        end
      end
      redirect_to root_path, notice: '在庫を更新しました'
    elsif params[:buy]# カートの銀行振込ボタン後
      purchased_history_save
      redirect_to root_path

    elsif params['payjp-token']# クレジット決済ボタンを押したあと
      begin
      purchased_history_save
      #payjp決済確定
      Payjp.api_key = ENV['PAYJP_TEST_SECRET_KEY']
      Payjp::Charge.create(
        :amount => @total_price,
        :card => params['payjp-token'],
        :currency => 'jpy',
      )
      redirect_to root_path
      rescue Payjp::CardError
        respond_to do |format|
          format.html { redirect_to root_path, notice: 'カードエラーが発生しました' }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
  end

  # sessioncreate POST   /purchased_histories/sessioncreate 商品詳細画面のsubmit後
  def sessioncreate
    # item_count
    item_count = params[:purchased_item][:item_count].to_i
    item = { item_count: item_count }
    # item_idはstring
    params[:item_id] = params[:purchased_item][:item_id]
    # session[:cart]に同じ商品があれば個数を増やす
    if session[:cart].has_key?(params[:item_id])
      session_item_count = session[:cart][params[:item_id]]["item_count"]
      session[:cart][params[:item_id]]["item_count"] = session_item_count.to_i + item_count
    else
      session[:cart][params[:item_id]] = item
      @item = Item.find(params[:item_id].to_i)
    end
    respond_to do |format|
      format.js
    end
  end

  # sessiondestroy GET    /purchased_histories/sessiondestroy/:id カート画面で商品削除ボタン
  def sessiondestroy
    session[:cart].delete(params[:id])
    @cart = session[:cart].map { |item_id, item_count| Item.find(item_id.to_i) }
    respond_to do |format|
      format.html { redirect_to purchased_histories_url, notice: 'Purchased history was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchased_history
      @purchased_history = PurchasedHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchased_history_params
      params.require(:purchased_history).permit(:user_name, :postal_code, :address, :phone_number, :email_address, :shipping, :created_at, :updated_at, purchased_items_attributes: [:id, :purchased_history_id, :item_id, :item_count, :_destroy])
    end

    def purchased_history_save
      if session[:cart].present?
        @purchased_history = PurchasedHistory.new
        @purchased_history.user_name = params['userinfo'][:user_name]
        @purchased_history.postal_code = params['userinfo'][:postal_code]
        @purchased_history.address = params['userinfo'][:address]
        @purchased_history.phone_number = params['userinfo'][:phone_number]
        @purchased_history.email_address = params['userinfo'][:email_address]
        @purchased_history.shipping = 0
        @purchased_history.save
        @total_price = 0
        params[:purchased_item].each do |item_id, item_count|
          item = Item.find(item_id.to_i)
          stock = Stock.find_by(item_id: item.id)
          item_count = item_count["item_count"].to_i
          if stock.stock_count >= item_count
            tax_included = (BigDecimal(item.item_price) * BigDecimal("1.08")).ceil
            tax_included = tax_included * item_count
            @total_price = @total_price + tax_included
            Stock.find_by(item_id: item.id).decrement!(:stock_count, item_count)
            @purchased_item = PurchasedItem.new
            @purchased_item.purchased_history_id = @purchased_history.id
            @purchased_item.item_id = item_id.to_i
            @purchased_item.item_count = item_count
            @purchased_item.save
            session[:cart].delete(item_id)
          end
        end
        @purchased_items = PurchasedItem.where(purchased_history_id: @purchased_history.id)
        PortfolioMailer.send_when_buy(@purchased_history).deliver
      end
    end
end

app/helpers/purchased_histories_helper.rb
module PurchasedHistoriesHelper
end

app/views/purchased_histories/_admin_cart.html.erb
<%= form_with url: purchased_histories_path do |form| %>
<!-- Modalヘッダー部分 -->
<div class="modal-header">
  <h5 class="modal-title" id="CartModalCenterTitle">管理者カート内容</h5>
  <button type="button" class="close" aria-label="Close" id="close_button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<!-- Modalボディ部分 -->
<div class="modal-body" id="card_have">
  <% @cart.each do |item| %>
    <!-- 先に税込金額と商品の個数を抜き出しておく -->
    <% tax_included = (BigDecimal(item.item_price) * BigDecimal("1.08")).ceil %>
      <% item_count = session[:cart][item.id.to_s]["item_count"].to_i %>
        <div class="card" id="item<%= item.id %>">
          <div class="cart-del-button">
            <%= link_to sessiondestroy_path(item.id), remote: true do %>
            <span aria-hidden="true">
              <i class="far fa-trash-alt"></i>
            </span>
          <% end %>
        </div>
        <% if item.post_images.present? %>
          <% item.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 600, 600, width: "100%" %>
          <% end %>
        <% else %>
          <%= image_tag '/images/no_image.jpg', width: "100%" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= item.item_name %></h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            1個
            <div class="inline-block tax_included"><%= tax_included %></div>円（税込み）
          </li>

          <!-- =====================ここで購入数の増減調節===================== -->
          <li class="list-group-item">
            <!-- ネストしたフォーム下部javascript管理 -->
            <%= form.fields_for "purchased_item[]", item do |purchased_item| %>
            <div class="inline-block count-size-textalign">
              <button type="button" class="minus btn btn-primary rounded-circle p-0" style="width:2rem;height:2rem;">-</button>
              <div class="item_count_div inline-block count-margin"><%= item_count %></div>
              <%= purchased_item.number_field :item_count, hidden: true, class: "item_count_input", value: item_count %>
              <button type="button" class="plus btn btn-primary rounded-circle p-0" style="width:2rem;height:2rem;">＋</button>
              <div class="inline-block">
                理論在庫<p class="inline-block text-right">
                  <%= Stock.find_by(item_id: item.id).stock_count %>
                </p>点
              </div>
            </div>
          <% end %>
        </li>
        <!-- =============================================================== -->

        <li class="list-group-item">
          合計
          <div class="total_price_div inline-block"><%= tax_included * item_count %></div>円（税込み）
        </li>
      </ul>
    </div>
  <% end %>
</div>
<!-- Modalボディ部分終了 -->
<!-- Modalフッター部分 -->
<div class="modal-footer">
  <div class="inline-block">
    総合計
    <div id="final_amount" class="inline-block"></div>円（税込み）
  </div>
  <%= form.submit "在庫更新", class: "btn btn-primary", name: "update" %>
  <%= form.submit "Close", class: "btn btn-secondary", name: "close", id: "form_end_button" %>
</div>
<% end %>

<script type="text/javascript">

finalamount();

$(".minus").click(function () {
  // 親要素を取得
  const parent_card = $(this).closest('.card');
  // 子要素.tax_includedの税込み金額を取得
  const item_price = parseInt(parent_card.find('.tax_included').text());
  // 子要素.item_count_divとその個数を取得
  const item_count_div = parent_card.find('.item_count_div');
  let item_count = parseInt(item_count_div.text());
  // 子要素.total_price_divとその金額を取得
  const total_price_div = parent_card.find('.total_price_div');
  let total_price = parseInt(total_price_div.text());
  // 子要素のhiddeninputとそのvalueを取得
  const item_count_input = parent_card.find('.item_count_input');
  if (total_price <= item_price && item_count == 0) {
    console.log("これ以上少なく出来ません");
  } else {
    total_price = total_price - item_price;
    item_count -= 1;
    item_count_div.text(item_count);
    item_count_input.val(item_count);
    console.log(item_count_input.val());
    total_price_div.text(total_price);

    finalamount();
  }
});
$(".plus").click(function () {
  // 親要素を取得
  const parent_card = $(this).closest('.card');
  // 子要素.tax_includedの税込み金額を取得
  const item_price = parseInt(parent_card.find('.tax_included').text());
  // 子要素.item_count_divとその個数を取得
  const item_count_div = parent_card.find('.item_count_div');
  let item_count = parseInt(item_count_div.text());
  // 子要素.total_price_divとその金額を取得
  const total_price_div = parent_card.find('.total_price_div');
  let total_price = parseInt(total_price_div.text());
  // 子要素のhiddeninputを取得
  const item_count_input = parent_card.find('.item_count_input');
  total_price = total_price + item_price;
  item_count += 1;
  item_count_div.text(item_count);
  item_count_input.val(item_count);
  console.log(item_count_input.val());
  total_price_div.text(total_price);

  finalamount();
});
$("#close_button").click(function () {
  $('#form_end_button').click();
});
</script>

app/views/purchased_histories/_cart.html.erb
<%= form_with url: purchased_histories_path do |form| %>

<!-- Modalヘッダー部分 -->
<div class="modal-header">
  <h5 class="modal-title" id="CartModalCenterTitle">カート内容</h5>
  <button type="button" class="close" aria-label="Close" id="close_button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<!-- Modalボディ部分 -->
<div class="modal-body" id="card_have">

  <% @cart.each do |item| %>
    <!-- 先に税込金額と商品の個数を抜き出しておく -->
    <% tax_included = (BigDecimal(item.item_price) * BigDecimal("1.08")).ceil %>
    <% stock_count = Stock.find_by(item_id: item.id).stock_count.to_i %>
    <% item_count = session[:cart][item.id.to_s]["item_count"].to_i %>
    <% item_count = stock_count if item_count >= stock_count %>
    <% if stock_count > 0 || item_count > 0 %>
    <div class="card" id="item<%= item.id %>">
      <div class="cart-del-button">
        <%= link_to sessiondestroy_path(item.id), remote: true do %>
        <span aria-hidden="true">
          <i class="far fa-trash-alt"></i>
        </span>
        <% end %>
      </div>
      <% if item.post_images.present? %>
        <% item.post_images.each do |image| %>
          <%= attachment_image_tag image, :image, :fill, 600, 600, width: "100%" %>
        <% end %>
      <% else %>
        <%= image_tag '/images/no_image.jpg', width: "100%" %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= item.item_name %></h5>
        <p class="card-text"><%= item.item_description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          1個
          <div class="inline-block tax_included"><%= tax_included %></div>円（税込み）
        </li>

        <!-- ===================ここで購入数の増減調節=================== -->
        <div class="item_stock" hidden="hidden"><%= stock_count %></div>
        <li class="list-group-item">
          <!-- ネストしたフォーム下部javascript管理 -->
          <%= form.fields_for "purchased_item[]", item do |purchased_item| %>
          <div class="inline-block count-size-textalign">
            <button type="button" class="minus btn btn-primary rounded-circle p-0" style="width:2rem;height:2rem;">-</button>
            <div class="item_count_div inline-block count-margin"><%= item_count %></div>
            <%= purchased_item.number_field :item_count, hidden: true, class: "item_count_input", value: item_count %>
            <button type="button" class="plus btn btn-primary rounded-circle p-0" style="width:2rem;height:2rem;">＋</button>
            <div class="inline-block">
              <p class="lacking-stock inline-block text-right"></p>
            </div>
          </div>
        </li>
      <!-- =========================================================== -->

        <li class="list-group-item">
          合計
          <div class="total_price_div inline-block"><%= tax_included * item_count %></div>円（税込み）
        </li>
      </ul>
    </div>
        <% end %>
      <% else %>
        <h5 class="card-title"><%= item.item_name %></h5>
        <p>上記の在庫が無くなった為購入できません。</p>
      <% end %>
    <% end %>
  </div>
  <!-- Modalボディ部分終了 -->

  <!-- =========================決済方法選択================================ -->
  <hr>
  <div class="mx-auto">
    <div id="credbutton" class="select-cash-button button-remove-background">
      <span class="pay-icon">
        <i class="fas fa-credit-card"></i>
        <span>クレジットカード</span>
      </span>
    </div>
    <div class="form-group count-margin display-none" id="cred-pay-form">
      <div class="">
        <h5>・送付先の情報を入力して下さい。</h5>
      </div>
      <%= form.fields_for "userinfo" do |userinfo| %>
        <%= userinfo.label :user_name, "お名前" %>
        <%= userinfo.text_field :user_name, class: "user-name-input form-control text_field_bottom", required: "true", placeholder: "山口　百恵 or 山口百恵" %>
        <%= userinfo.label :postal_code, "〒"%>
        <%= userinfo.text_field :postal_code, class: "postal-code-input form-control text_field_bottom", required: "true", placeholder: "123-4567 or 1234567" %>
        <%= userinfo.label :address, "住所"%>
        <%= userinfo.text_field :address, class: "address-input form-control text_field_bottom", required: "true", placeholder: "県名からお書き下さい" %>
        <div class="">
          <h5>・お客様のご連絡先を入力して下さい。</h5>
        </div>
        <%= userinfo.label :phone_number, "電話番号"%>
        <%= userinfo.telephone_field :phone_number, class: "phone-number-input form-control text_field_bottom", required: "true", type: "tel", inputmode: "tel", placeholder: "090-1234-5678 or 09012345678" %>
        <%= userinfo.label :email_address, "メールアドレス"%>
        <%= userinfo.text_field :email_address, class: "email-address-input form-control text_field_bottom", required: "true", type: "email", placeholder: "abc@abc.abc" %>
      <% end %>
        <script src="https://checkout.pay.jp/" class="payjp-button" data-key="<%= ENV['PAYJP_TEST_PUBLIC_KEY'] %>"></script>
      </div>

    <div id="bankbutton" class="select-cash-button button-remove-background">
      <span class="pay-icon">
        <i class="fas fa-piggy-bank"></i>
        <span>銀行振込</span>
      </span>
    </div>

    <div class="form-group count-margin display-none" id="bank-pay-form">
        <h5>・送付先の情報を入力して下さい。</h5>
      <div class="">
      <%= form.fields_for "userinfo" do |userinfo| %>
        <%= userinfo.label :user_name, "お名前" %>
        <%= userinfo.text_field :user_name, class: "user-name-input form-control text_field_bottom", required: "true", placeholder: "山口　百恵 or 山口百恵" %>
        <%= userinfo.label :postal_code, "〒"%>
        <%= userinfo.text_field :postal_code, class: "postal-code-input form-control text_field_bottom", required: "true", placeholder: "123-4567 or 1234567" %>
        <%= userinfo.label :address, "住所"%>
        <%= userinfo.text_field :address, class: "address-input form-control text_field_bottom", required: "true", placeholder: "県名からお書き下さい" %>
      </div>
      <div class="">
        <h5>・お客様のご連絡先を入力して下さい。</h5>
      </div>
        <%= userinfo.label :phone_number, "電話番号"%>
        <%= userinfo.telephone_field :phone_number, class: "phone-number-input form-control text_field_bottom", required: "true", type: "tel", inputmode: "tel", placeholder: "090-1234-5678 or 09012345678" %>
        <%= userinfo.label :email_address, "メールアドレス"%>
        <%= userinfo.text_field :email_address, class: "email-address-input form-control text_field_bottom", required: "true", type: "email", placeholder: "abc@abc.abc" %>
      <% end %>
      <%= form.submit "購入", class: "btn btn-primary", name: "buy" %>
    </div>
  </div>
  <br>
<!-- ======================================================================= -->

<!-- Modalフッター部分 -->
<div class="modal-footer">
  <div class="inline-block">
    合計
    <div id="final_amount" class="inline-block"></div>円（税込み）
  </div>
  <%= form.submit "Close", class: "btn btn-secondary", name: "close", id: "form_end_button", formnovalidate: "true" %>
</div>
<% end %>

<script type="text/javascript">
// 総合計算出
finalamount();
// ========================商品ごとのカウント制御===================================
$(".minus").click(function () {
  // 親要素を取得
  const parent_card = $(this).closest('.card');
  // 子要素.tax_includedの税込み金額を取得
  const item_price = parseInt(parent_card.find('.tax_included').text());
  // 子要素.item_count_divとその個数を取得
  const item_count_div = parent_card.find('.item_count_div');
  let item_count = parseInt(item_count_div.text());
  // 子要素.total_price_divとその金額を取得
  const total_price_div = parent_card.find('.total_price_div');
  let total_price = parseInt(total_price_div.text());
  // 子要素のhiddeninputとそのvalueを取得
  const item_count_input = parent_card.find('.item_count_input');
  if (total_price <= item_price && item_count == 1) {
    console.log("これ以上少なく出来ません");
  } else {
    total_price = total_price - item_price;
    item_count -= 1;
    item_count_div.text(item_count);
    item_count_input.val(item_count);
    console.log(item_count_input.val());
    total_price_div.text(total_price);

    finalamount();
  }
});
$(".plus").click(function () {
  // 親要素を取得
  const parent_card = $(this).closest('.card');
  // 子要素.lacking-stockの要素を取得
  const lacking_stock = parent_card.find('.lacking-stock');
  // 子要素.item_stockの在庫数を取得
  const item_stock = parseInt(parent_card.find('.item_stock').text());
  // 子要素.tax_includedの税込み金額を取得
  const item_price = parseInt(parent_card.find('.tax_included').text());
  // 子要素.item_count_divとその個数を取得
  const item_count_div = parent_card.find('.item_count_div');
  let item_count = parseInt(item_count_div.text());
  // 子要素.total_price_divとその金額を取得
  const total_price_div = parent_card.find('.total_price_div');
  let total_price = parseInt(total_price_div.text());
  // 子要素のhiddeninputを取得
  const item_count_input = parent_card.find('.item_count_input');
  if (item_count == item_stock) {
    lacking_stock.text("在庫がありません");
    console.log("在庫がありません");
  } else {
    total_price = total_price + item_price;
    item_count += 1;
    item_count_div.text(item_count);
    item_count_input.val(item_count);
    console.log(item_count_input.val());
    total_price_div.text(total_price);
  }
  finalamount();
});
// =============================================================================

// ==================================削除関連====================================
// クリックしたら他のところもクリック
$("#close_button").click(function () {
  //モーダル閉じる
  $('#form_end_button').click();
});
// =============================================================================

// ==============================決済方法選択制御==================================
$("#credbutton").click(function () {
  console.log('hi');
  if ($('#bank-pay-form').is(':visible')) {
    $('#bank-pay-form').slideUp();
  };
  $('#cred-pay-form').slideDown();
});

$("#bankbutton").click(function () {
  console.log('hi');
  if ($('#cred-pay-form').is(':visible')) {
    $('#cred-pay-form').slideUp();
  };
  $('#bank-pay-form').slideDown();
  $('button').prop('disabled', true);
});
// =============================================================================

// ==============================フォーム制御==============================
//相互同時入力
$('.user-name-input').on("keyup change", function () {
  $(".user-name-input").val($(this).val());
});
$('.postal-code-input').on("keyup change", function () {
  $(".postal-code-input").val($(this).val());
});
$('.address-input').on("keyup change", function () {
  $(".address-input").val($(this).val());
});
$('.phone-number-input').on("keyup change", function () {
  $(".phone-number-input").val($(this).val());
});
$('.email-address-input').on("keyup change", function () {
  $(".email-address-input").val($(this).val());
});
//フォームエンター制御変更
  $("input").keydown(function(e) {
    if ((e.which && e.which === 13) || (e.keyCode && e.keyCode === 13)) {
      return false;
    } else {
      return true;
    }
  });
// =============================================================================
</script>

app/views/purchased_histories/_cart_add.html.erb
<%= button_tag class: "cart-list-position button-remove-background" do %>
<div class="cart-item-list" id="cartitem<%= item.id %>">
  <% if item.post_images.present? %>
    <% item.post_images.each do |image| %>
      <div>
        <%= attachment_image_tag image, :image, :fill, 400, 400, class: "rounded-circle shadow circle-color" %>
      </div>
    <% end %>
  <% else %>
    <div>
      <%= image_tag '/images/no_image.jpg', size: '400✕400', class: "rounded-circle shadow circle-color" %>
    </div>
  <% end %>
</div>
<% end %>

app/views/purchased_histories/_cart_update.html.erb
<% if @cart.present? %>
  <% @cart.each do |item| %>
    <%= button_tag class: "cart-list-position button-remove-background" do %>
    <div class="cart-item-list" id="cartitem<%= item.id %>">
      <% if item.post_images.present? %>
        <% item.post_images.each do |image| %>
          <div>
            <%= attachment_image_tag image, :image, :fill, 400, 400, class: "rounded-circle shadow circle-color" %>
          </div>
        <% end %>
      <% else %>
        <div>
          <%= image_tag '/images/no_image.jpg', size: '400✕400', class: "rounded-circle shadow circle-color" %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
<% end %>

app/views/purchased_histories/create.js.erb
$("#CartModalCenter").modal("hide")

app/views/purchased_histories/new.js.erb
// index.html.erb中のDivに対して、新規作成用のformをレンダリング
console.log('hi');
<% if admin_signed_in? %>
  $("#CartItem").html("<%= escape_javascript(render 'admin_cart', cart: @cart, purchased_history: @purchased_history, purchased_item: @purchased_item) %>");
<% else %>
  $("#CartItem").html("<%= escape_javascript(render 'cart', cart: @cart, purchased_history: @purchased_history, purchased_item: @purchased_item) %>");
<% end %>
  // デフォルトのbootstrapでmodalを開いても良いが、タイミングが早すぎてrender間に合わない
  $("#CartModalCenter").modal("show");

app/views/purchased_histories/sessioncreate.js.erb
$("#ItemModalCenter").modal("hide");
<% if @item.present? %>
$("#cart-icon").append("<%= escape_javascript(render 'cart_add', item: @item) %>");
<% end %>

app/views/purchased_histories/sessiondestroy.js.erb
// index.html.erb中のDivに対して、新規作成用のformをレンダリング
console.log('hi')
$("#item<%= params[:id] %>").fadeOut().queue(function() {
  this.remove();
  <% unless session[:cart].present? %>
    $("#CartModalCenter").modal("hide");
  <% end %>
});
$("#cartitem<%= params[:id] %>").fadeOut();
$("#cart-icon").html("<%= escape_javascript(render 'cart_update', item: @item) %>");