config/routes.rb
Rails.application.routes.draw do

  # =========================デバイスの機能を絞る設定==============================
  devise_for :admins, skip: :all

  devise_scope :admin do
    get 'login', to: 'devise/sessions#new', as: 'new_admin_session'
    post 'login', to: 'devise/sessions#create', as: 'admin_session'
    delete 'logout', to: 'devise/sessions#destroy', as: 'destroy_admin_session'
  end
  # ===========================================================================

  # トップページをitemsのindexに設定
  root 'items#index'

  # namespaceでadmin配下にitemsを配置
  namespace :admin do
    resources :items
    resources :purchased_histories, only: [:index, :show]
    put 'statuschange/:id', to: 'items#statuschange', as: 'statuschange'
    get 'confirm/:id', to: 'items#confirm', as: 'confirm'
    put 'shippingchange/:id', to: 'purchased_histories#shippingchange', as: 'shippingchange'
  end

  # 一般のページ
  resources :items, only: [:index, :show, :create]
  resources :purchased_histories, only: [:new, :create]
  post 'purchased_histories/sessioncreate', to: 'purchased_histories#sessioncreate', as: 'sessioncreate'
  get 'purchased_histories/sessiondestroy/:id', to: 'purchased_histories#sessiondestroy', as: 'sessiondestroy'

  # refilegem用
  resources :post_images, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    acts_as_paranoid
  # ==========================アソシエーション====================================
  has_many :post_images
  has_many :item_tags
  has_many :tags, through: :item_tags
  has_many :purchased_items
  has_many :purchased_histories, through: :purchased_items
  has_one  :stock
  # ===========================================================================

  # ============================gem要設定=======================================
  # refile用
  accepts_attachments_for :post_images, attachment: :image
  # ===========================================================================

  # ====================formにhasmanyをネストさせる===============================
  accepts_nested_attributes_for :stock, allow_destroy: true
  accepts_nested_attributes_for :item_tags, allow_destroy: true
  accepts_nested_attributes_for :tags
  # ===========================================================================


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::Base
  # 上記の < Admin::Baseでbase.rbを継承するように指示
  before_action :authenticate_admin!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET admin_items GET    /admin/items 管理者画面のトップページ
  def index
    if params[:search].present?
      # Tagを検索しItemを取り出す
      tags = Tag.where('tag_name LIKE ?', "%#{params[:search]}%")
      # ユーザー名を検索しPurchasedHistoryを取り出す
      purchased_histories = PurchasedHistory.where('user_name LIKE ?', "%#{params[:search]}%")
      if tags.present?
        # タグが取り出せた場合
        item_tags = tags.map { |tag| ItemTag.where(tag_id: tag.id) }
        @items = item_tags.flatten!.map { |item_tag| Item.find_by(id: item_tag.item_id) }.uniq
        # @searchedは次jsファイルの条件分岐用
        @searched = 'item'
      elsif purchased_histories.present?
        # ユーザー名が取り出せた場合
        @items_with_deleted = Item.with_deleted
        @purchased_histories = purchased_histories.order(created_at: "DESC")
        @searched = 'username'
      else
        # タグが見つからない場合通常表示
        @items = Item.all.order(created_at: "DESC")
        @items_with_deleted = Item.with_deleted
        @purchased_histories = PurchasedHistory.all.order(created_at: "DESC")
        @searched = 'all'
      end
    else
      # 通常表示
      @items = Item.all.order(created_at: "DESC")
      @items_with_deleted = Item.with_deleted
      @purchased_histories = PurchasedHistory.all.order(created_at: "DESC")
      @searched = 'all'
    end
  end

  # GET admin_item GET    /admin/items/:id アイテムのQRコード表示
  def show
    @item = Item.find(params[:id])
    # svgでqr生成
    @qr = RQRCode::QRCode.new(@item.item_qr).as_svg.html_safe
  end

  # new_admin_item GET    /admin/items/new アイテム新規登録フォーム表示
  def new
    @item = Item.new
    @tags = Tag.new
    # refileで画像を投稿できるようにしている
    @item.post_images.build
    @item.item_description = "まねきねこはねこです。"
    @item.build_stock
  end

  # admin_items POST   /admin/items アイテム新規登録フォームの登録
  def create
    # gem cocoonによりネストした増殖フォームは上手に保存してくれている
    @item = Item.new(item_params)
    @tag = Tag.new(tag_params)
    respond_to do |format|
      if @item.save
        # 一個目のタグ新規追加フォームは以下で制御
        if @tag.tag_name?
          # タグが空欄の場合保存しないようにする
          @tag.save
          ItemTag.create(item_id: @item.id, tag_id: @tag.id)
        end
        # QRコードのURLを生成
        @item.item_qr = "https://portfolio.amamo.site/#Item#{@item.id}"
        @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
        format.js   { @status = "success"}
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
        format.js   { @status = "fail" }
      end
    end
  end

  # edit_admin_item GET    /admin/items/:id/edit アイテムの編集ページ
  def edit
    @item = Item.find(params[:id])
    @tags = Tag.new
  end

  # admin_item PUT    /admin/items/:id アイテム編集登録
  def update
    # gem cocoonによりネストした増殖フォームは上手に保存してくれている
    @item = Item.find(params[:id])
    @tag = Tag.new(tag_params)
    respond_to do |format|

      if @item.update(item_params)
        # 一個目のタグ新規追加フォームは以下で制御
        if @tag.tag_name?
          # タグが空欄の場合保存しないようにする
          @tag.save
          ItemTag.create(item_id: @item.id, tag_id: @tag.id)
        end
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
        format.js   { @status = "success"}
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
        format.js   { @status = "fail" }
      end
    end
  end

  # admin_statuschange PUT    /admin/statuschange/:id item_active変更
  def statuschange
    @item = Item.find(params[:id])
    if @item.item_active == 0
      @item.item_active = 1
      @item.save
    else
      @item.item_active = 0
      @item.save
    end
  end

  # admin_confirm GET    /admin/confirm/:id 商品削除確認画面
  def confirm
    @item = Item.find(params[:id])
  end

  # admin_item DELETE /admin/items/:id 商品削除確認画面から商品の削除
  def destroy
    respond_to do |format|
      if @item.destroy
        format.html { redirect_to admin_items_path, notice: 'Item was successfully destroyed.' }
        format.json { head :no_content }
        format.js   { @status = "success"}
      else
        format.html { redirect_to admin_items_path, notice: 'Item was error destroyed.' }
        format.json { head :no_content }
        format.js   { @status = "fail" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(
        :item_name, :item_description, :item_image_id, :item_qr, :item_price, :item_active,
        post_images_images: [],
        stock_attributes: [:id, :item_id, :stock_count],
        tags_attributes: [:id, :tag_name, :_destroy],
        tag_ids: [])
      # 複数画像を投稿できるように[]をつけている
      # フォームにhasoneのstockを含めている
    end

    def tag_params
      params.require(:tag).permit(:tag_name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # items GET    /items トップページ
  def index
    # カートで使用するSession確認
    if session[:cart] == nil
      session[:cart] = {}
    else
      @cart = session[:cart].map { |item_id, item_count| Item.find(item_id.to_i) }
    end
    # 商品検索
    @items = if params[:search].present?
      # Tagを検索しItemを取り出す
      tags = Tag.where('tag_name LIKE ?', "%#{params[:search]}%")
      if tags.present?
        item_tags = tags.map { |tag| ItemTag.where(tag_id: tag.id) }
        @items = item_tags.flatten!.map { |item_tag| Item.find_by(id: item_tag.item_id) }.uniq
      else
        # タグが見つからない場合
        Item.all.order(created_at: "DESC")
      end
    else
      # 通常表示
      Item.all.order(created_at: "DESC")
    end
  end

  # item GET    /items/:id アイテムの詳細ページ
  def show
    @item = Item.find(params[:id])
    @tax_included = (BigDecimal(@item.item_price) * BigDecimal("1.08")).ceil
    @purchased_history = PurchasedHistory.new
    @purchased_item = PurchasedItem.new
  end

  def create
    # アップルペイ本番仕様の場合以下を利用
    # begin
    # payjp決済確定
    # Payjp.api_key = ENV['PAYJP_TEST_SECRET_KEY']
    # Payjp::Charge.create(
    #   :amount => "1000",
    #   :card => params['payjp-token'],
    #   :currency => 'jpy',
    # )
    # purchased_history_save
    # redirect_to root_path
    # rescue Payjp::CardError
    #   respond_to do |format|
    #     format.html { redirect_to root_path, notice: 'カードエラーが発生しました' }
    #   end
    # end
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_history_params
      params.require(:purchase_history).permit(:user_name, :postal_code, :address, :phone_number, :email_address, :shipping, purchased_items_attributes: [:id, :purchased_history_id, :item_id, :item_count, :_destroy])
      # 複数画像を投稿できるように[]をつけている
      # フォームにhasoneのstockを含めている
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_cart_add.html.erb
    <%= button_tag class: "cart-list-position button-remove-background" do %>
    <div class="cart-item-list">
      <% if item.post_images.present? %>
        <% item.post_images.each do |image| %>
          <div>
            <%= attachment_image_tag image, :image, :fill, 400, 400, class: "rounded-circle shadow circle-color" %>
          </div>
        <% end %>
      <% else %>
        <div>
          <%= image_tag 'no_image.jpg', size: '400✕400', class: "rounded-circle shadow circle-color" %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/items/_searched.html.erb
<% if items.present? %>
  <% items.compact.each do |item| %>
    <% if item.item_active == 1 %>
      <%= link_to item, class: "col-6 col-md-3 top-margin-item button-remove-background", remote: true,id: "Item#{item.id}", data: {target: "#Item#{item.id}"} do %>
        <% if item.post_images.present? %>
          <% item.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 400, 400, class: "rounded-circle shadow circle-color mx-auto d-block width-change-item" %>
          <% end %>
        <% else %>
          <%= image_tag '/images/no_image.jpg', width: "100%", class: "rounded-circle shadow circle-color mx-auto d-block width-change-item" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/items/_show.html.erb
<!-- Modalボディ部分 -->
<%= form_with url: sessioncreate_path do |form| %>
<% stock = Stock.find_by(item_id: item.id).stock_count %>
  <div class="modal-body">
    <div class="card">
      <% if item.post_images.present? %>
        <% item.post_images.each do |image| %>
          <%= attachment_image_tag image, :image, :fill, 600, 600, width: "100%" %>
        <% end %>
      <% else %>
        <%= image_tag '/images/no_image.jpg', width: "100%" %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title" id="item_name"><%= item.item_name %></h5>
        <p class="card-text"><%= item.item_description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          1個
          <div class="inline-block"><%= tax_included %></div>円（税込み）
        </li>
        <li class="list-group-item">
          <!-- ネストしたフォーム下部javascript管理 -->
          <%= form.fields_for :purchased_item do |purchased_item| %>
          <%= purchased_item.number_field :item_id, hidden: true, value: item.id %>
          <div class="inline-block count-size-textalign">
            <button id="minus" type="button" class="btn btn-primary rounded-circle p-0" style="width:2rem;height:2rem;">-</button>
            <% if stock == 0 %>
              <div id="item_count_div" class="inline-block count-margin">0</div>
              <%= purchased_item.number_field :item_count, hidden: true, id: "item_count_input", value: "0" %>
            <% else %>
              <div id="item_count_div" class="inline-block count-margin">1</div>
              <%= purchased_item.number_field :item_count, hidden: true, id: "item_count_input", value: "1" %>
            <% end %>
            <button id="plus" type="button" class="btn btn-primary rounded-circle p-0" style="width:2rem;height:2rem;">＋</button>
            <% if admin_signed_in? %>
              <div class="inline-block" id="stock_field" style="cursor: pointer">
                理論在庫<p class="inline-block text-right" id="stock">
                  <%= stock %>
                </p>点
              </div>
            <% else %>
              <div class="inline-block">
                <% if stock == 0 %>
                  <p id="lacking-stock" class="inline-block text-right">在庫がありません</p>
                <% else %>
                  <p id="lacking-stock" class="inline-block text-right"></p>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </li>
      <li class="list-group-item">
        合計
        <div id="total_price_div" class="inline-block"><%= tax_included %></div>円（税込み）
      </li>
    </ul>
    <% unless stock == 0 %>
      <div class="card-body mx-auto" id="pay">
        <div id='notice' style="display:none;"></div>
            <div id="apple-pay-button-wrapper" style="display:none;">
              <div id="apple-pay-button" class="apple-pay-button apple-pay-button-black"></div>
            </div>
      </div>
    <% end %>
  </div>
</div>
<!-- Modalボディ部分終了 -->
<!-- Modalフッター部分 -->
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  <% if admin_signed_in? || (!admin_signed_in? && stock >= 1) %>
    <%= form.submit "カートに追加", class: "btn btn-primary" %>
  <% end %>
</div>
<% end %>

<script type="text/javascript">
// ========================商品ごとのカウント制御===================================
$("#minus").click(function () {
  // rubyから商品金額税込みを取得
  const item_price = parseInt(<%= tax_included.to_json %>);
  // lacking-stock要素を取得
  const lacking_stock = $("#lacking-stock");
  // pay要素を取得
  const pay = $("#pay");
  // item_count_div要素を取得、購入数は更新される
  const item_count_div = $("#item_count_div");
  // item_count_divの現在の購入数を取得
  let item_count = parseInt(item_count_div.text());
  // item_count_divの要素を取得、合計金額は更新される
  const total_price_div = $("#total_price_div");
  // total_price_divの合計金額を取得
  let total_price = parseInt(total_price_div.text());
  // item_count_inputの要素を取得する
  const item_count_input = $("#item_count_input");
  if (total_price <= item_price && item_count == 0) {
    pay.hide();
    console.log("これ以上少なく出来ません");
  } else {
    total_price = total_price - item_price;
    item_count -= 1;
    item_count_div.text(item_count);
    item_count_input.val(item_count);
    total_price_div.text(total_price);
    lacking_stock.text("");
  }
});
$("#plus").click(function () {
  // rubuから在庫数を取得
  const item_stock = <%= Stock.find_by(item_id: item.id).stock_count.to_i.to_json %>
  // rubyから商品金額税込みを取得
  const item_price = parseInt(<%= tax_included.to_json %>);
  // lacking-stock要素を取得
  const lacking_stock = $("#lacking-stock");
  // pay要素を取得
  const pay = $("#pay");
  // item_count_div要素を取得、購入数は更新される
  const item_count_div = $("#item_count_div");
  // item_count_divの現在の購入数を取得
  let item_count = parseInt(item_count_div.text());
  // item_count_divの要素を取得、合計金額は更新される
  const total_price_div = $("#total_price_div");
  // total_price_divの合計金額を取得
  let total_price = parseInt(total_price_div.text());
  // item_count_inputの要素を取得する
  const item_count_input = $("#item_count_input");
  if (item_count == item_stock && <%= admin_signed_in?.to_json %> == false) {
    lacking_stock.text("在庫がありません");
    console.log("在庫がありません");
  } else {
    total_price = total_price + item_price;
    item_count += 1;
    item_count_div.text(item_count);
    item_count_input.val(item_count);
    total_price_div.text(total_price);
    pay.show();
  }
});
// 管理者の場合理論在庫をクリックすることにより理論在庫からスタート可能
$("#stock_field").click(function (){
  const stock = parseInt($("#stock").text());
  $("#item_count_input").val(stock);
  $("#item_count_div").text(stock);
});
// ============================================================================

// ============================applepay制御=====================================
Payjp.setPublicKey("<%= ENV['PAYJP_TEST_PUBLIC_KEY'] %>");
// applePayが可能な端末であるか確認
function checkAvailabilityHandler(available) {
  if (available) {
    document.getElementById('apple-pay-button-wrapper').style.display = 'block';
    document.getElementById('notice').style.display = 'none';
  } else {
    document.getElementById('apple-pay-button-wrapper').style.display = 'none';
    document.getElementById('notice').style.display = 'block';
  }
}
function onClick() {
  var paymentRequest = {
    countryCode: 'JP',
    currencyCode: 'JPY',
    requiredShippingContactFields: ["postalAddress", "name", "phone", "email"],
    total: {
      label: $("#item_name").text(),
      amount: $("#total_price_div").text()
    }
  };
  var session = Payjp.applePay.buildSession(paymentRequest, function (result) {
    console.log(result);
    // サーバーにPAY.JPのトークンを渡して、決済完了後にApplePayのペイメントシートを閉じる
    $.post("/items", {token: result.token.id}).done(function () {
      session.completePayment(ApplePaySession.STATUS_SUCCESS);
    }).fail(function () {
      session.completePayment(ApplePaySession.STATUS_FAILURE);
    });
    document.getElementById('result').innerText = 'Token = ' + result.token.id;
    session.completePayment(ApplePaySession.STATUS_SUCCESS);
  }, function (e) {
    console.error(e);
    alert(e.error.message);
  });
  session.begin();
}
document.getElementById('apple-pay-button').addEventListener('click', onClick);
Payjp.applePay.checkAvailability(checkAvailabilityHandler);
// ======================================================================
</script>

app/views/items/index.js.erb
$('#searched').html("<%= escape_javascript(render 'searched', items: @items) %>");
$("html,body").animate({scrollTop:$('#searched').offset().top});

app/views/items/show.js.erb
// index.html.erb中のDivに対して、新規作成用のformをレンダリング
console.log('hi')
$("#ShowItem").html("<%= escape_javascript(render 'show', item: @item, tax_included: @tax_included, purchased_history: @purchased_history,purchased_item: @purchased_item) %>")
// デフォルトのbootstrapでmodalを開いても良いが、タイミングが早すぎてrender間に合わない
$("#ItemModalCenter").modal("show")