config/routes.rb
Rails.application.routes.draw do

  # =========================デバイスの機能を絞る設定==============================
  devise_for :admins, skip: :all

  devise_scope :admin do
    get 'login', to: 'devise/sessions#new', as: 'new_admin_session'
    post 'login', to: 'devise/sessions#create', as: 'admin_session'
    delete 'logout', to: 'devise/sessions#destroy', as: 'destroy_admin_session'
  end
  # ===========================================================================

  # トップページをitemsのindexに設定
  root 'items#index'

  # namespaceでadmin配下にitemsを配置
  namespace :admin do
    resources :items
    resources :purchased_histories, only: [:index, :show]
    put 'statuschange/:id', to: 'items#statuschange', as: 'statuschange'
    get 'confirm/:id', to: 'items#confirm', as: 'confirm'
    put 'shippingchange/:id', to: 'purchased_histories#shippingchange', as: 'shippingchange'
  end

  # 一般のページ
  resources :items, only: [:index, :show, :create]
  resources :purchased_histories, only: [:new, :create]
  post 'purchased_histories/sessioncreate', to: 'purchased_histories#sessioncreate', as: 'sessioncreate'
  get 'purchased_histories/sessiondestroy/:id', to: 'purchased_histories#sessiondestroy', as: 'sessiondestroy'

  # refilegem用
  resources :post_images, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/purchased_history.rb
class PurchasedHistory < ApplicationRecord
  # ==========================アソシエーション====================================
  has_many :purchased_items
  has_many :items, through: :purchased_items
  # ===========================================================================
  
  # ====================formにhasmanyをネストさせる===============================
  accepts_nested_attributes_for :purchased_items, allow_destroy: true
  # ===========================================================================
end

app/controllers/admin/purchased_histories_controller.rb
class Admin::PurchasedHistoriesController < Admin::Base
  before_action :set_purchased_history, only: [:show, :edit, :update, :destroy]

  # admin_purchased_histories GET    /admin/purchased_histories 注文履歴表示画面
  def index
    @purchased_histories = PurchasedHistory.all
  end

  # admin_purchased_history GET    /admin/purchased_histories/:id 注文履歴詳細表示
  def show
    @purchased_history = PurchasedHistory.find(params[:id])
    @purchased_items = PurchasedItem.where(purchased_history_id: @purchased_history.id)
    @items_with_deleted = Item.with_deleted
  end

  # admin_shippingchange PUT    /admin/shippingchange/:id 注文のshipping変更
  def shippingchange
    @purchased_history = PurchasedHistory.find(params[:id])
    if @purchased_history.shipping == 0
      @purchased_history.shipping = 1
      @purchased_history.save
    else
      @purchased_history.shipping = 0
      @purchased_history.save
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchased_history
      @purchased_history = PurchasedHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchased_history_params
      params.require(:purchased_history).permit(:user_name, :postal_code, :address, :phone_number, :email_address, :shipping, :created_at, :updated_at)
    end
end

app/controllers/purchased_histories_controller.rb
class PurchasedHistoriesController < ApplicationController
  before_action :set_purchased_history, only: [:show, :edit, :update, :destroy]

  # GET /purchased_histories/new
  def new
    @cart = session[:cart].map { |item_id, item_count| Item.find(item_id.to_i) }
    @purchased_history = PurchasedHistory.new
    @purchased_item = PurchasedItem.new
    respond_to do |format|
      format.js
    end
  end

  # purchased_histories POST   /purchased_histories カート画面フォームのsubmit後
  def create
    if params[:close]# カートの閉じるボタン後
      if session[:cart].present?
        session[:cart] = params[:purchased_item]
      end
    elsif params[:update]# カートの在庫更新ボタン後
      if session[:cart].present?
        params[:purchased_item].each do |item_id, item_count|
          item = Item.find(item_id.to_i)
          stock = Stock.find_by(item_id: item.id)
          stock.stock_count = item_count["item_count"].to_i
          stock.save
          session[:cart].delete(item_id)
        end
      end
      redirect_to root_path, notice: '在庫を更新しました'
    elsif params[:buy]# カートの銀行振込ボタン後
      purchased_history_save
      redirect_to root_path

    elsif params['payjp-token']# クレジット決済ボタンを押したあと
      begin
      purchased_history_save
      #payjp決済確定
      Payjp.api_key = ENV['PAYJP_TEST_SECRET_KEY']
      Payjp::Charge.create(
        :amount => @total_price,
        :card => params['payjp-token'],
        :currency => 'jpy',
      )
      redirect_to root_path
      rescue Payjp::CardError
        respond_to do |format|
          format.html { redirect_to root_path, notice: 'カードエラーが発生しました' }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
  end

  # sessioncreate POST   /purchased_histories/sessioncreate 商品詳細画面のsubmit後
  def sessioncreate
    # item_count
    item_count = params[:purchased_item][:item_count].to_i
    item = { item_count: item_count }
    # item_idはstring
    params[:item_id] = params[:purchased_item][:item_id]
    # session[:cart]に同じ商品があれば個数を増やす
    if session[:cart].has_key?(params[:item_id])
      session_item_count = session[:cart][params[:item_id]]["item_count"]
      session[:cart][params[:item_id]]["item_count"] = session_item_count.to_i + item_count
    else
      session[:cart][params[:item_id]] = item
      @item = Item.find(params[:item_id].to_i)
    end
    respond_to do |format|
      format.js
    end
  end

  # sessiondestroy GET    /purchased_histories/sessiondestroy/:id カート画面で商品削除ボタン
  def sessiondestroy
    session[:cart].delete(params[:id])
    @cart = session[:cart].map { |item_id, item_count| Item.find(item_id.to_i) }
    respond_to do |format|
      format.html { redirect_to purchased_histories_url, notice: 'Purchased history was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchased_history
      @purchased_history = PurchasedHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchased_history_params
      params.require(:purchased_history).permit(:user_name, :postal_code, :address, :phone_number, :email_address, :shipping, :created_at, :updated_at, purchased_items_attributes: [:id, :purchased_history_id, :item_id, :item_count, :_destroy])
    end

    def purchased_history_save
      if session[:cart].present?
        @purchased_history = PurchasedHistory.new
        @purchased_history.user_name = params['userinfo'][:user_name]
        @purchased_history.postal_code = params['userinfo'][:postal_code]
        @purchased_history.address = params['userinfo'][:address]
        @purchased_history.phone_number = params['userinfo'][:phone_number]
        @purchased_history.email_address = params['userinfo'][:email_address]
        @purchased_history.shipping = 0
        @purchased_history.save
        @total_price = 0
        params[:purchased_item].each do |item_id, item_count|
          item = Item.find(item_id.to_i)
          stock = Stock.find_by(item_id: item.id)
          item_count = item_count["item_count"].to_i
          if stock.stock_count >= item_count
            tax_included = (BigDecimal(item.item_price) * BigDecimal("1.08")).ceil
            tax_included = tax_included * item_count
            @total_price = @total_price + tax_included
            Stock.find_by(item_id: item.id).decrement!(:stock_count, item_count)
            @purchased_item = PurchasedItem.new
            @purchased_item.purchased_history_id = @purchased_history.id
            @purchased_item.item_id = item_id.to_i
            @purchased_item.item_count = item_count
            @purchased_item.save
            session[:cart].delete(item_id)
          end
        end
        @purchased_items = PurchasedItem.where(purchased_history_id: @purchased_history.id)
        PortfolioMailer.send_when_buy(@purchased_history).deliver
      end
    end
end

app/helpers/purchased_histories_helper.rb
module PurchasedHistoriesHelper
end

app/views/admin/purchased_histories/_shippingchange.html.erb
<% if purchased_history.shipping == 0 %>
  <%= link_to '未発送', admin_shippingchange_path(purchased_history), remote: true, method: :put, class: "btn btn-outline-light active table-innercustom-a text-danger" %>
<% else %>
  <%= link_to '発送済', admin_shippingchange_path(purchased_history), remote: true, method: :put, class: "btn active btn-outline-light table-innercustom-a text-success" %>
<% end %>

app/views/admin/purchased_histories/_show.html.erb
<!-- Modalボディ部分 -->
<div class="modal-body">

  <div class="card">
    <div class="card-body">
      <dl>
        <dt>注文日</dt>
        <dd><%= purchased_history.created_at.strftime('%Y年%m月%d日') %></dd>

        <dt>注文者</dt>
        <dd><%= purchased_history.user_name %></dd>

        <dt>メールアドレス</dt>
        <dd><%= purchased_history.email_address %></dd>

        <dt>電話番号</dt>
        <dd><%= purchased_history.phone_number %></dd>

        <dt>郵便番号</dt>
        <dd>〒<%= purchased_history.postal_code %></dd>

        <dt>住所</dt>
        <dd><%= purchased_history.address %></dd>
      </dl>
    </div>
  </div>
  <!-- 総合合計金額の計算 -->
  <% final_price = 0 %>
  <% purchased_items.each do |purchased_item| %>
  <% item = @items_with_deleted.with_deleted.find(purchased_item.item_id) %>
  <% item_price = item.item_price %>
  <% tax_included_item_price = (BigDecimal(item_price) * BigDecimal("1.08")).ceil %>
  <% total_price = tax_included_item_price * purchased_item.item_count.to_i %>
  <% final_price = final_price + total_price %>
  <div class="card">
    <% if item.post_images.present? %>
      <% item.post_images.each do |image| %>
        <%= attachment_image_tag image, :image, :fill, 400, 400, class: "mx-auto d-block width-change-item" %>
      <% end %>
    <% else %>
      <%= image_tag '/images/no_image.jpg', width: "100%", class: "rounded-circle shadow circle-color mx-auto d-block width-change-item" %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= item.item_name %></h5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        1個
        <div class="inline-block"><%= tax_included_item_price %></div>円（税込み）
      </li>
      <li class="list-group-item">
        <%= purchased_item.item_count %>個
      </li>
      <li class="list-group-item">
        合計
        <div class="inline-block"><%= total_price %></div>円（税込み）
      </li>
    </ul>
  </div>
  <% end %>
</div>
<!-- Modalボディ部分終了 -->

<!-- Modalフッター部分 -->
<div class="modal-footer">
  <div class="inline-block">
    総合計
    <div class="inline-block"><%= final_price %></div>円（税込み）
  </div>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/admin/purchased_histories/shippingchange.js.erb
$("#<%= "shippingchange#{@purchased_history.id}" %>").html("<%= escape_javascript(render 'shippingchange', purchased_history: @purchased_history) %>");

app/views/admin/purchased_histories/show.js.erb
// index.html.erb中のDivに対して、新規作成用のformをレンダリング
console.log('hi');
$("#ShowHistory").html("<%= escape_javascript(render 'show', purchased_history: @purchased_history, purchased_items: @purchased_items) %>");
// デフォルトのbootstrapでmodalを開いても良いが、タイミングが早すぎてrender間に合わない
$("#purchaseHistoryModal").modal("show");